version: "3.8"
services:
  # -------------------------
  # Nginx Reverse Proxy
  # -------------------------
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx

  # -------------------------
  # Next.js Client
  # -------------------------
  client:
    image: gaaravu0/pickleball-client:latest
    container_name: nextjs-client
    restart: always
    environment:
      - VIRTUAL_HOST=sanpickleball.xyz,www.sanpickleball.xyz
      - LETSENCRYPT_HOST=sanpickleball.xyz,www.sanpickleball.xyz
      - LETSENCRYPT_EMAIL=your-email@example.com
    expose:
      - "8080"

  # -------------------------
  # Node.js Server
  # -------------------------
  server:
    image: gaaravu0/pickleball-server:latest
    container_name: node-server
    restart: always
    environment:
      - VIRTUAL_HOST=sanpickleball.xyz,www.sanpickleball.xyz
      - LETSENCRYPT_HOST=sanpickleball.xyz,www.sanpickleball.xyz
      - LETSENCRYPT_EMAIL=your-email@example.com
      - MONGODB_URI=mongodb://mongo:27017/
    expose:
      - "2704"
    depends_on:
      - mongo

  # -------------------------
  # MongoDB
  # -------------------------
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  certs:
