version: "3.8"
services:
  client:
    image: gaaravu0/pickleball-client:latest
    container_name: nextjs-client
    restart: always
    ports:
      - "8080:8080"

  server:
    image: gaaravu0/pickleball-server:latest
    container_name: node-server
    restart: always
    ports:
      - "2704:2704"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"     # public HTTP 
      - "443:443"   # public HTTPS (needed for SSL later)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server

volumes:
  mongo-data:
