server {
    listen 80;

    server_name sanpickleball.xyz www.sanpickleball.xyz;

    # Proxy requests to Node.js API
    location /api/ {
        proxy_pass http://server:2704/api/;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;

        # Optional: longer timeouts for APIs
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Proxy requests to Next.js client
    location / {
        proxy_pass http://client:8080;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }
}
